# Generated by Django 5.1.5 on 2025-01-20 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college_admin', '0003_remove_company_company_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='company_email',
        ),
    ]
