# Generated by Django 5.1.5 on 2025-01-20 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_admin', '0004_remove_company_company_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.FileField(upload_to='media/Company-Logo'),
        ),
    ]
