# Generated by Django 5.1.5 on 2025-01-21 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college_admin', '0006_remove_student_age_student_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_name',
        ),
    ]
