# Generated by Django 5.1.5 on 2025-01-22 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_admin', '0007_remove_student_student_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='hod_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to='media/student_image'),
        ),
    ]
