# Generated by Django 5.1.5 on 2025-01-22 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_admin', '0010_alter_company_status_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('vacancy', models.IntegerField()),
                ('location', models.CharField(max_length=100)),
                ('cv', models.FileField(upload_to='media/cv')),
                ('opening_date', models.DateField(auto_now_add=True)),
                ('closing_date', models.DateField(blank=True, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college_admin.department')),
            ],
        ),
        migrations.CreateModel(
            name='AppliedStudents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intial_round1', models.CharField(choices=[('Pass', 'Pass'), ('Fail', 'Fail'), ('Pending', 'Pending')], default='Pending', max_length=100)),
                ('tech_round2', models.CharField(choices=[('Pass', 'Pass'), ('Fail', 'Fail'), ('Pending', 'Pending')], default='Pending', max_length=100)),
                ('is_passed', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_st', to='college_admin.student')),
                ('jobpost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_stu', to='college_admin.jobposts')),
            ],
        ),
        migrations.CreateModel(
            name='TechInterview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('start_time', models.DateTimeField()),
                ('status', models.CharField(max_length=200)),
                ('applied', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tech_applied', to='college_admin.appliedstudents')),
            ],
        ),
    ]
