# Generated by Django 5.1.5 on 2025-01-22 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_admin', '0011_jobposts_appliedstudents_techinterview'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposts',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_jobs', to='college_admin.company'),
        ),
    ]
