# Generated by Django 5.1.5 on 2025-01-22 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college_admin', '0012_jobposts_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobposts',
            old_name='post_name',
            new_name='languages',
        ),
    ]
