# Generated by Django 5.1.5 on 2025-01-22 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_admin', '0013_rename_post_name_jobposts_languages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliedstudents',
            name='jobpost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_stuu', to='college_admin.jobposts'),
        ),
        migrations.AlterField(
            model_name='company',
            name='status',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Revoked', 'Revoked'), ('Pending', 'Pending')], default='Pending', max_length=100, null=True),
        ),
    ]
