# Generated by Django 5.1.5 on 2025-01-22 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_admin', '0014_alter_appliedstudents_jobpost_alter_company_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='status',
            field=models.CharField(blank=True, choices=[('Approved', 'Approved'), ('Revoked', 'Revoked'), ('Pending', 'Pending')], default='Pending', max_length=100, null=True),
        ),
    ]
