# Generated by Django 5.1.5 on 2025-02-03 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college_admin', '0015_alter_company_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_active',
        ),
    ]
