# Generated by Django 5.1.5 on 2025-02-05 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_admin', '0017_customuser_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobposts',
            name='cv',
        ),
        migrations.AddField(
            model_name='appliedstudents',
            name='cv',
            field=models.FileField(null=True, upload_to='media/cv'),
        ),
    ]
