# Generated by Django 5.1.5 on 2025-02-05 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_admin', '0018_remove_jobposts_cv_appliedstudents_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposts',
            name='salary',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
