# Generated by Django 5.1.5 on 2025-02-05 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college_admin', '0019_jobposts_salary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobposts',
            old_name='languages',
            new_name='skills',
        ),
    ]
