# Generated by Django 5.1.5 on 2025-03-05 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_admin', '0022_appliedstudents_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposts',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
