# Generated by Django 5.1.5 on 2025-03-05 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_admin', '0023_jobposts_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techinterview',
            name='link',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='techinterview',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='techinterview',
            name='status',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
