# Generated by Django 5.1.5 on 2025-03-05 20:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_admin', '0026_assessment_assessmentquestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessmentquestion',
            name='assessment',
        ),
        migrations.CreateModel(
            name='AssessmentSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_questions', models.IntegerField()),
                ('current_question', models.TextField(blank=True, null=True)),
                ('current_model_answer', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('student_answer', models.TextField()),
                ('model_answer', models.TextField()),
                ('marks', models.FloatField()),
                ('feedback', models.TextField()),
                ('answered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college_admin.assessmentsession')),
            ],
        ),
        migrations.DeleteModel(
            name='Assessment',
        ),
        migrations.DeleteModel(
            name='AssessmentQuestion',
        ),
    ]
