# Generated by Django 5.1.5 on 2025-03-05 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_admin', '0027_remove_assessmentquestion_assessment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentanswer',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='assessment_videos/'),
        ),
    ]
